name: Ping on release

on:
  workflow_run:
    workflows: ["Build and release"]  # name of the other workflow
    types: [completed]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger external webhook
        env:
          SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$(echo -n '{}' | openssl dgst -sha256 -hmac "$SECRET" | cut -d' ' -f2)" \
            -d '{}' \
            https://caph.info/hooks/github-webhook