name: Rotate releases

on:
  release:
    # Use the canonical release event types. `published` fires when a release
    # is published; `created` covers creation. Avoid unknown/non-standard
    # types which may not trigger.
    types: [created, published]

jobs:
  rotate-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Get releases
        id: releases
        run: |
          curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq '.[].id' > release_ids.txt

      - name: Delete old releases
        run: |
          # Adjust this to your criteria for "old" releases, e.g., keep the latest 3
          releases_to_delete=$(tail -n +4 release_ids.txt)  # Delete releases older than the latest 3
          for release_id in $releases_to_delete; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/$release_id
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}